name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
# core: 8.x
hidden: true

# Information added by Drupal.org packaging script on 2019-07-04
version: '8.7.4'
core: '8.x'
project: 'drupal'
datestamp: 1562225734
